#!/usr/bin/env bash
# AIOS sandbox entrypoint (root, PID 2 under tini, cap_drop ALL + sshd's minimum). Prepares the host key,
# the agent's authorized_keys, /workspace, the SSH session environment and the optional GitHub token,
# then execs sshd with its log lines wrapped as JSON. Any arguments are exec'd instead (debugging).
set -euo pipefail
umask 022

readonly AGENT=agent
readonly HOST_KEY=/etc/ssh/keys/ssh_host_ed25519_key
readonly AUTH_SRC=${AIOS_AUTHORIZED_KEYS:-/opt/aios/ssh/authorized_keys}
readonly AUTH_DIR=/etc/ssh/authorized_keys
readonly ENV_CONF=/etc/ssh/sshd_config.d/00-aios-env.conf
readonly SECRETS_DIR=/run/aios
readonly WORKSPACE=${WORKSPACE_ROOT:-/workspace}

log() {
  local level=$1
  shift
  jq -nc --arg level "$level" --arg msg "$*" \
    '{ts: (now | todate), level: $level, service: "sandbox", component: "entrypoint", msg: $msg}' >&2
}
die() {
  log error "$*"
  exit 1
}

if (($#)); then
  exec "$@"
fi

ensure_host_key() {
  install -d -m 0755 "$(dirname "$HOST_KEY")"
  if [[ ! -s $HOST_KEY || ! -s $HOST_KEY.pub ]]; then
    rm -f -- "$HOST_KEY" "$HOST_KEY.pub"
    ssh-keygen -q -t ed25519 -N '' -C aios-sandbox -f "$HOST_KEY"
    log info "generated a new host key (clients will see a new fingerprint)"
  fi
  chmod 0600 "$HOST_KEY"
  chmod 0644 "$HOST_KEY.pub"
}

# Copies the mounted authorized_keys into a root-owned file the agent cannot modify, validating every key
# and adding `restrict,pty` to option-less keys (no forwarding even if sshd_config regressed).
install_authorized_keys() {
  local line count=0 staged
  [[ -r $AUTH_SRC && -s $AUTH_SRC ]] ||
    die "missing or empty $AUTH_SRC: run 'make sandbox-keys' on the host (mounts data/sandbox/keys/authorized_keys)"
  install -d -m 0755 "$AUTH_DIR"
  staged=$(mktemp "$AUTH_DIR/.$AGENT.XXXXXX")
  while IFS= read -r line || [[ -n $line ]]; do
    line=${line%$'\r'}
    [[ -z ${line//[[:space:]]/} || $line == \#* ]] && continue
    ssh-keygen -l -f /dev/stdin <<<"$line" >/dev/null 2>&1 || {
      rm -f -- "$staged"
      die "invalid public key in $AUTH_SRC: ${line:0:40}..."
    }
    if [[ $line =~ ^(ssh-|ecdsa-|sk-) ]]; then
      line="restrict,pty $line"
    fi
    printf '%s\n' "$line" >>"$staged"
    count=$((count + 1))
  done <"$AUTH_SRC"
  ((count > 0)) || {
    rm -f -- "$staged"
    die "no public keys in $AUTH_SRC"
  }
  chmod 0644 "$staged"
  mv -f -- "$staged" "$AUTH_DIR/$AGENT"
  log info "authorized $count key(s) for $AGENT"
}

ensure_workspace() {
  local uid
  uid=$(id -u "$AGENT")
  install -d "$WORKSPACE"
  # Docker creates a missing bind-mount source as root; hand it to the agent (needs CAP_CHOWN only).
  if [[ $(stat -c %u "$WORKSPACE") != "$uid" ]]; then
    chown "$AGENT:$AGENT" "$WORKSPACE"
    log info "chowned $WORKSPACE to $AGENT"
  fi
}

# Container env never reaches SSH sessions, so selected settings are passed with one sshd SetEnv line.
write_session_env() {
  local name value home vars
  home=$(getent passwd "$AGENT" | cut -d: -f6)
  [[ $WORKSPACE =~ ^/[A-Za-z0-9._/-]*$ ]] || die "WORKSPACE_ROOT has unsupported characters: $WORKSPACE"
  vars="LANG=C.UTF-8 WORKSPACE_ROOT=$WORKSPACE COREPACK_ENABLE_DOWNLOAD_PROMPT=0 COREPACK_ENABLE_AUTO_PIN=0"
  vars+=" GIT_TERMINAL_PROMPT=0 DO_NOT_TRACK=1"
  for name in AIOS_CHECK_TIMEOUT AIOS_TASK_CHECK_TIMEOUT AIOS_CHECK_TAIL_LINES AIOS_CLONE_TIMEOUT; do
    value=${!name:-}
    [[ -n $value ]] || continue
    [[ $value =~ ^[1-9][0-9]{0,5}$ ]] || die "$name must be a positive integer (got '$value')"
    vars+=" $name=$value"
  done
  # edge worker URL for skills/knowledge/transcript_to_notes when it isn't http://edge:8080 (Railway: edge-gw)
  if [[ -n ${AIOS_EDGE_URL:-} ]]; then
    [[ $AIOS_EDGE_URL =~ ^https?://[A-Za-z0-9._-]+(:[0-9]{1,5})?/?$ ]] || die "AIOS_EDGE_URL must be http(s)://host[:port]"
    vars+=" AIOS_EDGE_URL=$AIOS_EDGE_URL"
  fi
  # System directories first: binaries the agent installs (go install, uv tool install, a cloned repo's
  # scripts) must never shadow aios-check, git, ssh or python3.
  vars+=" PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin:$home/go/bin:$home/.local/bin"
  install -d -m 0755 "$(dirname "$ENV_CONF")"
  printf '# generated by the entrypoint at container start\nSetEnv %s\n' "$vars" >"$ENV_CONF.tmp"
  mv -f -- "$ENV_CONF.tmp" "$ENV_CONF"
}

# GITHUB_TOKEN goes only to a tmpfs file readable by the agent (for aios-git-credential), never to disk
# and never into session environments (where `env` would leak it into transcripts).
install_github_token() {
  local file=$SECRETS_DIR/github_token token=${GITHUB_TOKEN:-}
  unset GITHUB_TOKEN
  rm -f -- "$file" 2>/dev/null || true
  [[ -n $token ]] || return 0
  if [[ ! -d $SECRETS_DIR || $(stat -f -c %T "$SECRETS_DIR") != tmpfs ]]; then
    log warn "GITHUB_TOKEN ignored: $SECRETS_DIR is not a tmpfs mount, refusing to write the token to disk"
    return 0
  fi
  [[ $token =~ ^[A-Za-z0-9_]+$ ]] || die "GITHUB_TOKEN has unexpected characters"
  (
    umask 0377
    printf '%s\n' "$token" >"$file"
  )
  chown "$AGENT:$AGENT" "$file"
  log info "GITHUB_TOKEN available to git over HTTPS for github.com"
}

ensure_host_key
install_authorized_keys
ensure_workspace
write_session_env
install_github_token
install -d -m 0755 /run/sshd # privilege-separation chroot
/usr/sbin/sshd -t || die "sshd configuration test failed"
log info "starting sshd; host key $(ssh-keygen -lf "$HOST_KEY.pub" | awk '{print $2}')"

# sshd -e writes plain lines ("error: ...", "fatal: ...", CRLF-terminated); wrap each one as a JSON log.
exec /usr/sbin/sshd -D -e 2> >(exec jq --unbuffered -Rc '
  sub("\r$"; "") as $m
  | {ts: (now | todate),
     level: (if ($m | startswith("fatal: ")) then "fatal"
             elif ($m | startswith("error: ")) then "error"
             elif ($m | test("^debug[0-9]?: ")) then "debug"
             else "info" end),
     service: "sandbox", component: "sshd", msg: $m}' >&2)
