"""Render config/litellm/config.yaml from config.template.yaml.

Keeps only deployments whose `os.environ/<KEY>` api_key is non-empty in .env, drops fallback
targets/sources for model groups that ended up empty, and enables the langfuse_otel callback
only when Langfuse keys are configured. Run via: uv run --with pyyaml infra/scripts/render-litellm-config.py
"""

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = ROOT / "config/litellm/config.template.yaml"
OUT = ROOT / "config/litellm/config.yaml"


def read_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.split(" #", 1)[0].strip().strip('"').strip("'")
    return env


def main() -> int:
    env = read_env(ROOT / ".env")
    cfg = yaml.safe_load(TEMPLATE.read_text())
    cfg = {k: v for k, v in cfg.items() if not k.startswith("x-")}

    kept, dropped = [], []
    for dep in cfg["model_list"]:
        key_ref = dep["litellm_params"].get("api_key", "")
        if isinstance(key_ref, str) and key_ref.startswith("os.environ/"):
            if not env.get(key_ref.removeprefix("os.environ/")):
                dropped.append(f'{dep["model_name"]} ({dep["litellm_params"]["model"]})')
                continue
        kept.append(dep)
    cfg["model_list"] = kept
    groups = {d["model_name"] for d in kept}

    rs = cfg.get("router_settings", {})
    for field in ("fallbacks", "context_window_fallbacks"):
        pruned = []
        for entry in rs.get(field, []):
            for src, targets in entry.items():
                targets = [t for t in targets if t in groups]
                if src in groups and targets:
                    pruned.append({src: targets})
        rs[field] = pruned

    ls = cfg.setdefault("litellm_settings", {})
    if env.get("LANGFUSE_PUBLIC_KEY") and env.get("LANGFUSE_SECRET_KEY"):
        ls["callbacks"] = ["langfuse_otel"]

    header = "# GENERATED by infra/scripts/render-litellm-config.py from config.template.yaml - do not edit\n"
    OUT.write_text(header + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True, width=200))
    print(f"model groups: {', '.join(sorted(groups))}")
    if dropped:
        print("omitted (no key): " + "; ".join(dropped))
    cloud = groups - {"local-qwen", "decider-local", "embed-local"}
    if not cloud:
        print("WARNING: no cloud provider key set - Hermes needs at least one >=64K-context model", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
